before

node.js:*
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
ReferenceError: foo is not defined
    at evalmachine.<anonymous>:*
    at Object.<anonymous> (*test*message*undefined_reference_in_new_context.js:*)
    at Module._compile (_module.js:*)
    at Object..js (_module.js:*)
    at Module.load (_module.js:*)
    at Function._load (_module.js:*)
    at Array.<anonymous> (_module.js:*)
    at EventEmitter._tickCallback (node.js:*)
